// Mocks generated by Mockito 5.4.2 from annotations
// in domain/test/usecases/search_products_use_case/execute.welltested_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:domain/models/product_model.dart' as _i6;
import 'package:domain/network_result/network_error.dart' as _i5;
import 'package:domain/repository/product_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i3.ProductRepository {
  MockProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.NetworkError, List<_i6.Product>>> getAllProducts(
    int? page,
    int? limit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllProducts,
          [
            page,
            limit,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.NetworkError, List<_i6.Product>>>.value(
                _FakeEither_0<_i5.NetworkError, List<_i6.Product>>(
          this,
          Invocation.method(
            #getAllProducts,
            [
              page,
              limit,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.NetworkError, List<_i6.Product>>>);
  @override
  _i4.Future<_i2.Either<_i5.NetworkError, _i6.Product>> getProductsDetails(
          int? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductsDetails,
          [productId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.NetworkError, _i6.Product>>.value(
                _FakeEither_0<_i5.NetworkError, _i6.Product>(
          this,
          Invocation.method(
            #getProductsDetails,
            [productId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.NetworkError, _i6.Product>>);
  @override
  _i4.Future<_i2.Either<_i5.NetworkError, List<_i6.Product>>>
      getProductsByQuery(String? query) => (super.noSuchMethod(
            Invocation.method(
              #getProductsByQuery,
              [query],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.NetworkError, List<_i6.Product>>>.value(
                _FakeEither_0<_i5.NetworkError, List<_i6.Product>>(
              this,
              Invocation.method(
                #getProductsByQuery,
                [query],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.NetworkError, List<_i6.Product>>>);
}
