USE firekart;

CREATE TABLE OTPRecords (
  id INT AUTO_INCREMENT PRIMARY KEY,
  phoneNumber VARCHAR(20) NOT NULL,
  otp VARCHAR(4) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  phoneNumber VARCHAR(20)
);

CREATE TABLE Address (
  id INT PRIMARY KEY AUTO_INCREMENT,
  userId INT,
  name VARCHAR(255) NOT NULL,
  pincode VARCHAR(10) NOT NULL,
  address TEXT NOT NULL,
  city VARCHAR(100) NOT NULL,
  state VARCHAR(100) NOT NULL,
  phoneNumber VARCHAR(20) NOT NULL,
  isDefault BOOLEAN NOT NULL,
  FOREIGN KEY (userId) REFERENCES Users(id)
);

CREATE TABLE Product (
  id INT PRIMARY KEY AUTO_INCREMENT,
  productId VARCHAR(255) NOT NULL,
  image VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  unit VARCHAR(50) NOT NULL,
  currency VARCHAR(10) NOT NULL,
  dealOfTheDay BOOLEAN NOT NULL,
  topProducts BOOLEAN NOT NULL,
  onSale BOOLEAN NOT NULL,
  currentPrice DECIMAL(10, 2) NOT NULL,
  actualPrice DECIMAL(10, 2) NOT NULL,
  quantityPerUnit DECIMAL(10, 2) NOT NULL,
  isProductAvailable BOOLEAN NOT NULL
);

CREATE TABLE Orders (
  id INT PRIMARY KEY AUTO_INCREMENT,
  userId INT NOT NULL,
  totalPrice DECIMAL(10, 2) NOT NULL,
  orderedAt DATETIME NOT NULL,
  orderStatus VARCHAR(50) NOT NULL,
  paymentId VARCHAR(255) NOT NULL,
  signature VARCHAR(255) NOT NULL,
  FOREIGN KEY (userId) REFERENCES Users(id)
);

CREATE TABLE OrderItem (
  id INT PRIMARY KEY AUTO_INCREMENT,
  orderId INT NOT NULL,
  productId INT NOT NULL,
  quantity INT NOT NULL,
  pricePerItem DECIMAL(10, 2) NOT NULL,
  FOREIGN KEY (orderId) REFERENCES Orders(id),
  FOREIGN KEY (productId) REFERENCES Product(id)
);

CREATE TABLE Cart (
  id INT PRIMARY KEY AUTO_INCREMENT,
  userId INT NOT NULL,
  productId INT NOT NULL,
  quantity INT NOT NULL,
  FOREIGN KEY (userId) REFERENCES Users(id),
  FOREIGN KEY (productId) REFERENCES Product(id)
);
